#!/bin/bash
# 
#   bumppkg
#  
#   Copyright (c) 2006 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

die()
{
	echo $0: $@
	exit 1
}

check_complex()
{
	if [ ! -f FrugalBuild ]; then
		die "Could not find FrugalBuild!"
	fi
	if [ "`grep -c sha1sums= FrugalBuild`" -gt 1 ]; then
		die "This FrugalBuild is too complex, update it manually!"
	fi
}

src_cleanup()
{
	local i workdir

	Fmessage "cleaning up old source files"
	i=`pwd`
	while true
	do
		if [ -e "$i/_darcs" ]; then
			break
		elif [ "$i" == "" ]; then
			break
		fi
		i=`echo $i|sed 's|\(.*\)/.*|\1|'`
	done
	root=$i
	workdir=`pwd|sed "s|$root||"`
	rootlist=`mktemp`
	worklist=`mktemp`
	darcsdir="_darcs/pristine"
	if [ ! -d $root/$darcsdir ]; then
		darcsdir="_darcs/current"
	fi
	ls $root/$darcsdir/$workdir >$rootlist
	ls >$worklist
	for i in `diff -u $rootlist $worklist|grep ^+[^+]|sed 's/^+//'`
	do
		rm -v $i
	done
	rm $rootlist $worklist
}

update_pkgver()
{
	Fmessage "updating \$pkgver and \$pkgrel"
	newpkgver=`chkworld |grep != |sed 's/.*!= \([^ ]*\) .*/\1/'`
	if [[ "$newpkgver" =~ " " ]] || [ -z "$newpkgver" ]; then
		die "Dunno what is the new version or this package is already up to date!"
	fi
	sed -i "s/^pkgver=.*/pkgver=$newpkgver/;s/^pkgrel=.*/pkgrel=1/;/# vim: ft=sh/d" FrugalBuild
}

src_download()
{
	Fmessage "downloading the new source"
	makepkg -dg
	if [ $? != 0 ]; then
		die "failed to download the source"
	fi

	if grep sha1sums= FrugalBuild; then
		Fmessage "updating \$sha1sums() in the FrugalBuild"
		if grep -q '^sha1sums.*)' FrugalBuild; then
			sed -i "/^sha1sums.*)/d" FrugalBuild
		else
			sed -i "/^sha1sums/,/)/d" FrugalBuild
		fi
		makepkg -dg >>FrugalBuild
	fi

	Fmessage "cleaning up the duplicated source files"
	rm -rf pkg src
}

do_build()
{
	sudo makepkg -c || die "build failed!"
	Fmessage "done, testing time!"
}

do_record()
{
	source FrugalBuild || die "failed to source the FrugalBuild!"
	echo -e "`date +"%a %b %d %H:%M:%S %Z %Y"`
`cat $root/_darcs/prefs/author`
$pkgname-$pkgver-$pkgrel-$CARCH
$@" | darcs rec -a --pipe
}

USE_COLOR="y"
. /usr/lib/frugalware/fwmakepkg
. /etc/makepkg.conf

if [ "$1" == "--record-only" ]; then
	do_record "$2"
	exit 0
fi
check_complex
update_pkgver
src_cleanup
src_download
do_build
if [ "$1" == "--record" ]; then
	do_record "$2"
	shift 2
fi

if [ "$1" == "--push" ]; then
	rf -k -c -f *-$CARCH.fpm
fi
