#!/bin/bash
# 
#   bumppkg
#  
#   Copyright (c) 2006 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

die()
{
	echo $0: $@
	exit 1
}

check_complex()
{
	if [ ! -f FrugalBuild ]; then
		die "Could not find FrugalBuild!"
	fi
	if [ "`grep -c sha1sums= FrugalBuild`" -gt 1 ]; then
		die "This FrugalBuild is too complex, update it manually!"
	fi
}

get_root()
{
	local i=`pwd`
	while true
	do
		if [ -e "$i/_darcs" ]; then
			break
		elif [ "$i" == "" ]; then
			break
		fi
		i=`echo $i|sed 's|\(.*\)/.*|\1|'`
	done
	echo $i
}

src_cleanup()
{
	local root i workdir

	Fmessage "cleaning up old source files"
	root="`get_root`"
	workdir=`pwd|sed "s|$root||"`
	rootlist=`mktemp`
	worklist=`mktemp`
	darcsdir="_darcs/pristine"
	if [ ! -d $root/$darcsdir ]; then
		darcsdir="_darcs/current"
	fi
	ls $root/$darcsdir/$workdir >$rootlist
	ls >$worklist
	for i in `diff -u $rootlist $worklist|grep ^+[^+]|sed 's/^+//'`
	do
		rm -v $i
	done
	rm $rootlist $worklist
}

update_pkgrel()
{
	local rel=$1
	[ -z "$rel" ] && rel=1
	sed -i "s/^pkgrel=.*/pkgrel=$rel/" FrugalBuild
}

update_pkgver()
{
	Fmessage "updating \$pkgver and \$pkgrel"
	newpkgver=`chkworld |grep != |sed 's/.*!= \([^ ]*\) .*/\1/'`
	if [[ "$newpkgver" =~ " " ]] || [ -z "$newpkgver" ]; then
		die "Dunno what is the new version or this package is already up to date!"
	fi
	sed -i "s/^pkgver=.*/pkgver=$newpkgver/;/# vim: ft=sh/d" FrugalBuild
}

src_download()
{
	Fmessage "running makepkg -dG"
	makepkg -dG
	if [ $? != 0 ]; then
		die "failed to run makepkg -dG"
	fi

	Fmessage "cleaning up the duplicated source files"
	rm -rf pkg src
}

do_build()
{
	sudo makepkg -c$1 || die "build failed!"
	Fmessage "done, testing time!"
}

# this can be replaced with repoman rec soon
do_record()
{
	source FrugalBuild || die "failed to source the FrugalBuild!"
	root="`get_root`"
	echo -e "`LANG= LC_ALL= date +"%a %b %d %H:%M:%S %Z %Y"`
`cat $root/_darcs/prefs/author`
$pkgname-$pkgver-$pkgrel-$CARCH
$@" | darcs rec -a --pipe .
}

USE_COLOR="y"
. /usr/lib/frugalware/fwmakepkg
. /etc/makepkg.conf

if [ "$1" == "--record-only" ]; then
	do_record "$2"
	exit 0
fi

if [ "$1" == "--rebuild" ]; then
	shift 1
	source FrugalBuild || die "failed to source the FrugalBuild!"
	update_pkgrel $(($pkgrel+1))
	do_build u
	if [ -n "$1" ]; then
		do_record "$1"
		shift 1
	fi
	if [ "$1" == "--push" ]; then
		repoman -k push
	fi
	exit 0
fi

check_complex
update_pkgver
update_pkgrel
src_cleanup
src_download
do_build
if [ "$1" == "--record" ]; then
	do_record "$2"
	shift 2
fi

if [ "$1" == "--push" ]; then
	repoman -k push
fi
