#!/bin/bash
# 
#   fblint for Frugalware
#  
#   Copyright (c) 2006 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

myver="0.6.5"

die()
{
	echo "$0: $@"
	exit 1
}

check()
{
	[ "$_fblint_verbose" ] && echo -n "checking for $1... "
	eval $2
	if [ "$?" = 0 ]; then
		[ "$_fblint_verbose" ] && echo "done."
		_fblint_done=$(($_fblint_done+1))
	else
		[ ! "$_fblint_verbose" -a ! "$_fblint_quiet" ] && echo -n "checking for $1... "
		[ "$_fblint_quiet" ] || echo "failed."
		_fblint_failed=$(($_fblint_failed+1))
	fi
}

get_root()
{
	local i
	i=`git rev-parse --git-dir 2>/dev/null`
	if [ -n "$i" ]; then
		echo `dirname $i`
		_scm=git
		return
	fi
	i=`pwd`
	while true
	do
		if [ -e "$i/_darcs" ]; then
			break
		elif [ "$i" == "" ]; then
			break
		fi
		i=`echo $i|sed 's|\(.*\)/.*|\1|'`
	done
	echo $i
	_scm=darcs
}

if [ "$1" = "--version" ]; then
	echo "fblint (pacman-tools) $myver"
	echo
	echo "Copyright (c) 2006 by Miklos Vajna <vmiklos@frugalware.org>"
	echo "This is free software; see the source for copying conditions.  There is NO"
	echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
	exit 0
fi

if [ "$1" = "--help" ]; then
	echo "usage: $0 [--help] | [--version] | [-q] [-v] [-p]"
	echo "       -q		quiet mode, exit with error if at least one test failed"
	echo "       -v		verbose node, output the passed tests, too"
	echo "       -p		buildscript [./FrugalBuild]"
	echo "       --help	this help"
	echo "       --version	version information"
	exit 0
fi

if [ "$1" = "-q" ]; then
	_fblint_quiet="y"
	shift 1
fi

if [ "$1" = "-v" ]; then
	_fblint_verbose="y"
	shift 1
fi

if [ "$1" = "-p" ]; then
	_fblint_fb="$2"
else
	_fblint_fb="FrugalBuild"
fi

_fblint_done="0"
_fblint_failed="0"
CHROOT=1
. /usr/lib/frugalware/fwmakepkg
. /etc/makepkg.conf

echo -n "Checking if FrugalBuild exists ... "
if [ -e $_fblint_fb ]; then
       echo "OK!"
else
       echo "Error! File to check does not exist!"
       exit 1
fi

check "no last modified line" "! grep -q -i '^# Last Modified: ' $_fblint_fb"
check "sbu" "grep -i -q \"^# Compiling Time: [~0-9\.]\+ SBU$\" $_fblint_fb"
check "maintainer" "grep -q '^# Maintainer: ' $_fblint_fb"
check "syntax errors" "source $_fblint_fb"
check "pkgname" "[ ! -z \"$pkgname\" ]"
check "uppercase letters in pkgname" "[[ ! \"$pkgname\" =~ \"[A-Z]\" ]]"
check "pkgver" "[ ! -z \"$pkgver\" ]"
check "hyphen-less pkgver" "[ ! `echo $pkgver | grep '-'` ]"
check "pkgrel" "[ ! -z "$pkgrel" ]"
check "hyphen-less pkgrel" "[ ! `echo $pkgrel | grep '-'` ]"
check "pkgdesc" "[ ! -z \"$pkgdesc\" ]"
check "url" "[ ! -z \"$url\" ]"
check "groups" "[ ! -z \"$groups\" ]"
check "valid first group" "! echo $groups |grep -q -- - || echo $groups|grep -q -- -extra$"
check "valid options()" "[ -z \"$(echo ${options[@]}|tr ' ' '\n' |grep -v '\(nodocs\|nostrip\|force\|nobuild\|nofakeroot\|scriptlet\|stick\)')\" ]"
check "archs" "[ ! -z \"$archs\" ]"
check "up2date" "[ ! -z \"`echo $up2date|sed 's/\$(/\\\\\$(/g'`\" ]"
check "md5sums/sha1sums/signatures" "[ ${#md5sums[@]} -gt 0 -o ${#sha1sums[@]} -gt 0 -o ${#signatures[@]} -gt 0 ]"
if [ ${#md5sums[@]} -gt 0 ]; then
	check "right number of md5sums" "[ ${#md5sums[@]} -eq ${#source[@]} ]"
fi
if [ ${#sha1sums[@]} -gt 0 ]; then
	check "right number of sha1sums" "[ ${#sha1sums[@]} -eq ${#source[@]} ]"
fi
if [ ${#signatures[@]} -gt 0 ]; then
	check "right number of signatures" "[ ${#signatures[@]} -eq ${#source[@]} ]"
fi

if [ ! -z "$subpkgs" ]; then
	for subpkg in "${subpkgs[@]}"
	do
		check "uppercase letters in subpkgs" "[[ ! \"$subpkg\" =~ \"[A-Z]\" ]]"
	done
	check "subdescs" "[ ! -z \"$subdescs\" ]"
	check "subgroups" "[ ! -z \"$subgroups\" ]"
	check "subarchs" "[ ! -z \"$subarchs\" ]"
	check "right number of subdescs" "[ \"${#subdescs[@]}\" = 0 ] || [ \"${#subdescs[@]}\" == \"${#subpkgs[@]}\" ]"
	check "right number of sublicense" "[ \"${#sublicense[@]}\" = 0 ] || [ \"${#sublicense[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subreplaces" \
		"[ \"${#subreplaces[@]}\" = 0 ] || [ \"${#subreplaces[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subgroups" "[ \"${#subgroups[@]}\" = 0 ] || [ \"${#subgroups[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subarchs" "[ \"${#subarchs[@]}\" = 0 ] || [ \"${#subarchs[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subdepends" "[ \"${#subdepends[@]}\" = 0 ] || [ \"${#subdepends[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subrodepends" \
		"[ \"${#subrodepends[@]}\" = 0 ] || [ \"${#subrodepends[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subremoves" "[ \"${#subremoves[@]}\" = 0 ] || [ \"${#subremoves[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subconflicts" \
		"[ \"${#subconflicts[@]}\" = 0 ] || [ \"${#subconflicts[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subprovides" \
		"[ \"${#subprovides[@]}\" = 0 ] || [ \"${#subprovides[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subbackup" "[ \"${#subbackup[@]}\" = 0 ] || [ \"${#subbackup[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of subinstall" "[ \"${#subinstall[@]}\" = 0 ] || [ \"${#subinstall[@]}\" = \"${#subpkgs[@]}\" ]"
	check "right number of suboptions" "[ \"${#suboptions[@]}\" = 0 ] || [ \"${#suboptions[@]}\" = \"${#subpkgs[@]}\" ]"
fi

if [ "`get_root`" = "frugalware-stable" ]; then
	check "unchanged pkgrel" "echo $pkgrel | grep -q '\(siwenna\|terminus\)'"
fi

[ "$_fblint_verbose" ] && echo "done: $_fblint_done, failed $_fblint_failed"

if [ $_fblint_failed -gt 0 ]; then
	exit 1
else
	exit 0
fi
