#!/bin/bash

if [ "$1" == "-h" -o "$1" == "--help" ]; then
	man fpmdiff
	exit $?
fi

if [ "$1" == "-v" -o "$1" == "--version" ]; then
	pacman-g2 -Q pacman-tools
	exit $?
fi

old=`mktemp`
new=`mktemp`

pacman-g2 -Ql -p $1|sed 's/^[^ ]\+ //' > $old
pacman-g2 -Ql -p $2|sed 's/^[^ ]\+ //' > $new

diff -U 0 $old $new | sed '1,2d;/^@/d'
rm -f $old $new
