#!/bin/bash

die()
{
	echo "genchangelog: $@"
	exit 1
}

strip_url()
{
	echo $1 | sed 's|^.*://.*/||g'
}
[ -z "$arch" ] && arch=`arch`
[ -z "$uploader" ] && uploader=`echo $HOME|sed 's|.*/\(.*\)$|\1|'`

if [ "$1" = "--repo" ]; then
	fwver=`echo $2 |sed 's/frugalware-//'`
	shift 2
fi

if [ "$1" = "--check" ]; then
	if [ "`echo $HOME|sed 's|.*/\(.*\)$|\1|'`" != "syncpkgd" ]; then
		. /etc/genchangelog.conf
		chkperm /home/ftp/pub/frugalware/frugalware-$fwver/docs/xml/teams.xml $2
		exit $?
	else
		exit 0
	fi
elif [ "$1" = "--clean" ]; then
	. /etc/genchangelog.conf
	../tools/fdb2db -b ../source/ -r frugalware -e $fwver -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -D -c $2
	exit 0
fi

# fake variable for fwmakepkg
CHROOT=1

. /usr/lib/frugalware/fwmakepkg

if [ ! -e Changelog ] || [ `stat -c %Y Changelog` -lt `stat -c %Y FrugalBuild` ]; then
	echo -n "running darcs changes... "
	darcs changes FrugalBuild > Changelog
	echo "done."
fi

CWD=`pwd`

CARCH=$arch source FrugalBuild || die "errors parsing the FrugalBuild"

. /etc/genchangelog.conf

. /etc/makepkg.conf

echo "downloading missing source files..."

for i in ${source[@]} ${signatures[@]}
do
	file=`strip_url $i`
	if [ ! -e $file ]; then
		echo "downloading $file..."
		$FTPAGENT $i
	fi
done

echo -n "updating mysql database... "
[ "$fwver" = "current" ] && reposuffix="-current"
cd ../../../frugalware-$arch
../tools/fdb2db -b ../source/ -r frugalware -e $fwver -f frugalware$reposuffix.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c $pkgname -l $uploader

if [ ! -z "$subpkgs" ]; then
	i=0
	for subpkg in "${subpkgs[@]}"
	do
		cd $CWD
		groups="${subgroups[$i]}"
		cd ../../../frugalware-$arch
		../tools/fdb2db -b ../source/ -r frugalware -e $fwver -f frugalware$reposuffix.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c "$subpkg" -s -n $pkgname -l $uploader
	done
fi

echo "done."
