#!/bin/bash

die()
{
	echo "genchangelog: $@"
	exit 1
}

strip_url()
{
	echo $1 | sed 's|^.*://.*/||g'
}
[ -z "$arch" ] && arch=`arch`
[ -z "$uploader" ] && uploader=`echo $HOME|sed 's|.*/\(.*\)$|\1|'`

if [ "$1" = "--repo" ]; then
	fwver=`echo $2 |sed 's/frugalware-//'`
	shift 2
fi

if [ "$1" = "--check" ]; then
	if [ "`echo $HOME|sed 's|.*/\(.*\)$|\1|'`" != "syncpkgd" ]; then
		. /etc/genchangelog.conf
		chkperm /home/ftp/pub/frugalware/frugalware-$fwver/docs/xml/teams.xml $2
		exit $?
	else
		exit 0
	fi
elif [ "$1" = "--clean" ]; then
	. /etc/genchangelog.conf
	# where are we?
	if [ "`pwd|sed 's|.*/\([^/]*\)/[^/]*|\1|'`" != "extra" ]; then
		../tools/fdb2db -b ../source/ -r frugalware -e $fwver -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -D -c $2
	else
		../../tools/fdb2db -b ../source/ -r extra -e $fwver -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -D -c $2
	fi
	exit 0
fi

# fake variable for fwmakepkg
CHROOT=1

. /usr/lib/frugalware/fwmakepkg

if [ ! -e Changelog ] || [ `stat -c %Y Changelog` -lt `stat -c %Y FrugalBuild` ]; then
	echo -n "running darcs changes... "
	darcs changes FrugalBuild > Changelog
	echo "done."
fi

CWD=`pwd`
repo=`pwd|sed 's|.*/\(.*\)/.*/.*/.*|\1|'`
if [ "$repo" != "extra" ]; then
	repo="frugalware"
fi

CARCH=$arch source FrugalBuild || die "errors parsing the FrugalBuild"

. /etc/genchangelog.conf

. /etc/makepkg.conf

echo "downloading missing source files..."

for i in ${source[@]} ${signatures[@]}
do
	file=`strip_url $i`
	if [ ! -e $file ]; then
		echo "downloading $file..."
		$FTPAGENT $i
	fi
done

echo -n "updating mysql database... "
[ "$fwver" = "current" ] && reposuffix="-current"
if [ "$repo" == "frugalware" ]; then
	cd ../../../frugalware-$arch
	../tools/fdb2db -b ../source/ -r frugalware -e $fwver -f frugalware$reposuffix.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c $pkgname -l $uploader
else
	cd ../../../frugalware-$arch
	../../tools/fdb2db -b ../source/ -r extra -e $fwver -f extra$reposuffix.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c $pkgname -l $uploader
fi

if [ ! -z "$subpkgs" ]; then
	i=0
	for subpkg in "${subpkgs[@]}"
	do
		cd $CWD
		groups="${subgroups[$i]}"
		if [ "$repo" = "frugalware" ] && echo $groups|sed 's/^\([^ ]*\) .*/\1/'|grep -q -- -extra$; then
			# special case: the subpkg is in extra while the main pkg is in frugalware
			cd ../../../extra/frugalware-$arch
			../../tools/fdb2db -b ../../source/ -r extra -e $fwver -f extra$reposuffix.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c "$subpkg" -s -n $pkgname -l $uploader
		else
			# the subpkg is in the same repo as the main one
			if [ "$repo" == "frugalware" ]; then
				cd ../../../frugalware-$arch
				../tools/fdb2db -b ../source/ -r frugalware -e $fwver -f frugalware$reposuffix.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c "$subpkg" -s -n $pkgname -l $uploader
			else
				cd ../../../frugalware-$arch
				../../tools/fdb2db -b ../source/ -r extra -e $fwver -f extra$reposuffix.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c $subpkg -s -n $pkgname -l $uploader
			fi
		fi
	done
fi

echo "done."
