#!/usr/bin/perl

use strict;
use Module::MakefilePL::Parse;
use Data::Dumper;

my $fh;
open $fh, 'Makefile.PL';
my $parser = Module::MakefilePL::Parse->new( join("", <$fh>) );
my $info   = $parser->required;

my $out = 'depends=(';
for (keys %{$info}) {
	$_ = lc;
	$_ = 'perl-'.$_;
	$_ =~ s/::/-/;
	$out .= "'$_' ";
}
chop $out;
$out .= ')';
print "$out\n";
