#!/bin/sh
# must be run as root
OWNTMPDIR=`mktemp -d /tmp/order.XXXXXX` || exit 1
echo -n | pacman -r $OWNTMPDIR -Sy $* | grep -- '-[0-9\.]\+' | sed 's/^Targets: //;s/\(-[0-9]\+\) \([a-z]\)/\1\n\2/g;s/^ \+\(.*\)/\1/' | sed 's/-[^-]\+-[^-]\+$//'
rm -rf $OWNTMPDIR
