#!/bin/bash

# (c) 2004 Vajna Miklos <vmiklos@frugalware.org>
# pacman-source for pacman
# distributed under GPL License

# version 0.7

usage()
{
	echo -e "Usage: $0 [-v] [-q] <pkgname>.
	-v   verbose mode
	-q   quick mode: do not download source tarballs, only buildscripts"
}

strnopkg="Package \"$1\" was not found."

if [ "$1" == "-v" ]; then
	verbose=1
	shift
fi

if [ "$1" == "-q" ]; then
	quickdl="_darcs/current/"
	shift
fi

if [ -z "$1" ]; then
	usage
	exit 1
fi

if ! pacman -Si $1 >/dev/null 2>&1; then
	echo $strnopkg
	exit 1
fi

confs=`cat /etc/pacman.conf |grep ^Include|sed 's/.* = \(.*\)/\1/'`
dump="wget --passive-ftp -O - -q"
wget="wget --passive-ftp -c -m --retr-symlinks"

echo -n "Searching for a mirror... "
repo=`pacman -Si $1|grep ^Repo|sed -n 's/.* \([^ ]*\)/\1/;1 p'`
dir=`grep ^Server /etc/pacman.d/$repo|sed -n 's/.* = \(.*\)/\1/;1 p'`
arch=`grep ^Server /etc/pacman.d/$repo |sed -n 's/.*-\(.*\)/\1/;1 p'`
cat=`pacman -Si $1 |grep ^G |sed 's/.* : \([^ ]*\) .*/\1/'`
echo "done."

mkdir $1 2>/dev/null || \
	{
		echo "Could not create directory: $1"
		echo "Have you downloaded the package yet?"
		exit 1
	}
cd $1 || exit 1
if [ "$verbose" == 1 ]; then
	echo "Downloading $1 source..."
	$wget $dir/../$quickdl/source/$cat/$1/
else
	echo -n "Downloading $1 source... "
	$wget $dir/../$quickdl/source/$cat/$1/ &>/dev/null
	echo "done."
fi
junk=`echo $dir|sed "s|^ftp://\(.*\)/frugalware-$arch|\1|"`/$quickdl/source/$cat/$1/

mv $junk* ./
rm -rf `echo $junk|cut -d/ -f1`

for i in `find * -type d`
do
	( cd $i && [ -e .listing ] && rm .listing )
done
