.TH "REPOMAN" "1" "July 2005" "Frugalware 0.3" "pacman-tools"
.SH NAME
repoman \- Frugalware's program to maintain packages via darcs and ssh
.SH SYNOPSIS
\fBrepoman\fR [\fIglobal options\fR] [\fIcommand\fR] [\fIcommand options\fR]
.SH DESCRIPTION
.BR repoman
is meant for Frugalware developers to upload or delete source
tarballs, fpm packages and generate changelogs.
.br
Note: \fBrepoman\fR only runs \fIinside\fR a darcs repository.
.SH USAGE
A typical package update should be done as follows:
.TP
1) Get the repo and set defaults.

.BR Note:
We recommend you to use a mirror server and the --partial option!

Example for the first time:

darcs get --partial http://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/

Example for the pacman-tools repo:

darcs get --partial http://darcs.frugalware.org/repos/pacman-tools

cd frugalware-current

echo "yourname <email@addr.ess>" > _darcs/prefs/author

echo 'username@darcs.frugalware.org:/home/ftp/pub/frugalware/frugalware-current' > _darcs/prefs/defaultrepo

Or, for the pacman-tools repo:

echo 'username@darcs.frugalware.org:/home/ftp/pub/other/pacman-tools/darcs' > _darcs/prefs/defaultrepo

echo 'push apply-as vmiklos' >> _darcs/prefs/defaults

Note: Here do not substituate my nick (vmiklos) with you nick!

.TP
2) Update the repo.

If you already got the repo a simple 'darcs pull' should be enough.

.TP
3) Make changes and build the package.

Now time to edit the FrugalBuild and make changes.

If you would like to add new file(s) to the source, run this:

darcs add xorg.install

To remove file(s) from the source, run this:

darcs remove 00-at-3.1.8r11-makefile.patch

Or if you would like to rename a file in the source, run this:

darcs mv 01-xorg-8.6.2-vmware-amd64.patch 02-xorg-6.8.2-vmware-amd64.patch

Then build the packages with 'makepkg -c', or better:

su -c 'makepkg -Ra'

.TP
4) Recording the changes.

Simply run 'darcs record'.

When recording the patch (if this is a package upgrade), its name must be $pkgname-$pkgver-$pkgrel-$arch (when answering to 'What is the patch name?').

For example:

xorg-6.8.2-2-i686

This is the same as the full package name without trailing .fpm.

.TP
5) Delete the old source package(s).

If you only do a rebuild, then, of course, skip this step. For example:

repoman del source/base/readline/readline-5.0.tar.gz

.TP
6) Push the FrugalBuild/.install/etc patch.

Here you only have to do a simple 'darcs push'.

This command uploads the changes you made locally to the server.

.TP
7) Upload the new source package(s).

If you only do a rebuild, then, of course, skip this step.

For example:

repoman up zsh-4.2.5.tar.bz2 /source/apps/zsh/

repoman up zsh-doc-4.2.5.tar.bz2 /source/apps/zsh/

.TP
8) Upload the new fpm package:

For example (see the 'up' command description for more details!):

repoman up sendmail-8.13.4-2-i686.fpm extra/frugalware-i686/

.TP
9) Delete the old fpm package.

For example:

repoman del frugalware-i686/xorg-6.8.2-4-i686.fpm

.TP
10) Generate a Changelog and update the .fdb database:

For example:

repoman cl base/perl

.SH COMMANDS
.TP
.BI cl|changelog " [repository/]category/package"
Generate a Changelog file from darcs patch comments.
.TP
.BI c|clean " [repository/]category/package"
Wipes out a package from the package database (fdb).
.TP
.BI del|delete " file"
Delete a file from the Frugalware Source Tree (FST).

Example: repoman del frugalware-i686/xorg-6.8.2-4-i686.fpm
.TP
.BI ls|list " directory [options]"
List the contents of a remote directory.

Example: repoman ls source/base/db/ -l
.TP
.BI m|merge " package"
Build a package from source and install it. You can configure the build
options in the makepkg_opts directive of /etc/repoman.conf.

By default repoman will install the missing dependencies with pacman, clean up
the leftover work files, install the package, and write the resulting package
to the current working directory.

.TP
.BI up|upload " source [destination]"
Upload a file to FST. Destination is [extra/]frugalware-<arch>. If the package
is in the extra repo, the extra/ prefix is required. <arch> currently can be
i686 or x86_64. The default value is frugalware-<arch>.

Example: repoman up sendmail-8.13.4-2-i686.fpm extra/frugalware-i686/
.TP
.BI upd|update " [repo]"
Update a repo in /var/fst. If the option repo parameter omitted, the repoman
will update the frugalware-current repo. If the frugalware-current repo not
yet exists, then repoman will download it (it may take some time!).

.TP
.BI s|search " [regexp]"
Search in those FrugalBuilds which are only available in source form. If the
optional regexp parameter omitted, it will list all source-only packages.

.SH OPTIONS
.TP
.B -h|--help
Show the help screen.
.TP
.B -v|--verbose
Give verbose output.
.SH ENVIRONMENT
\fBrepoman\fR utilizes the following environment variable:
.PP
.Vb 2
REPOMAN_LOGIN                Use different login name than the current.
.Vb 2

arch                         Update different architecture of the .fdb
                             than repoman is running on.
.SH AUTHORS
Written by Miklos Vajna and Laszlo Dvornik.
.SH "REPORTING BUGS"
Please report bugs to the <frugalware-users@frugalware.org> mailing list.
.SH "SEE ALSO"
.BR darcs (1),
.BR pacman (8)
