#!/bin/bash

# (c) 2005 Vajna Miklos <vmiklos@frugalware.org>
# repoman for Frugalware
# distributed under GPL License

function usage()
{
	cat <<EOF
Usage: `basename $0` [global options] [command] [command options]

Commands:
cl|changelog [repository/]category/package  Generate a Changelog file
del|delete file                             Delete a file from FST.
ls|list directory                           List a directory in FST.
up|upload source destination                Upload a file to FST.

Global options:
-v|--verbose  Give verbose output.
-h|--help     Show this help screen.
EOF
}

msg()
{
	echo -e "\033[1;32m==>\033[1;0m \033[1;1m$1\033[1;0m" >&2
}

delete()
{
	# strip leading / and any ..
	file=`echo $1|sed 's|^/||;s|\.\./||g'`
	msg "Deleting file: $file"
	if [ "$verbose" == 0 ]; then
		ssh $lopts $host "sudo -u $sudouser rm $path_to_repo/$file"
	else
		ssh $lopts $host "sudo -u $sudouser rm -v $path_to_repo/$file"
	fi
	
}

upload()
{
	if [ "$#" -le 0 ]; then
		echo "Too few parameters!"
		usage
		exit 1
	fi
	if [ -z "$2" ]; then
		dest="frugalware-`uname -m`"
	else
		# strip leading / and any ..
		dest=`echo $2 |sed 's|^/||;s|\.\./||g'`
	fi
	src=$1
	name=`basename $src`
	msg "Requesting a temporarily file"
	tmp=`ssh $lopts darcs.frugalware.org mktemp 2>/dev/null`
	msg "Uploading file: $src (to $tmp)"
	scp $src $cpopts$host:$tmp
	msg "Copying to $dest"
	ssh $lopts $host "chmod 644 $tmp; sudo -u vmiklos cp $tmp $path_to_repo/$dest/$name && rm $tmp"
}

list()
{
	msg "Fetching contents of directory: $1"
	dir=$1
	shift 1
	ssh $lopts $host "ls $* $path_to_repo/$dir"
}

changelog()
{
	msg "Generating Changelog for $1"
	if echo $1 |grep -q '^[^/]\+/[^/]\+/[^/]\+$'; then
		repo=`echo $1 |sed 's|\([^/]\+\)/[^/]\+/[^/]\+|\1|'`
		group=`echo $1 |sed 's|[^/]\+/\([^/]\+\)/[^/]\+|\1|'`
		pkgname=`echo $1 |sed 's|[^/]\+/[^/]\+/\([^/]\+\)|\1|'`
	elif echo $1 |grep -q '^[^/]\+/[^/]\+$'; then
		repo="frugalware"
		group=`echo $1 |sed 's|\([^/]\+\)/[^/]\+|\1|'`
		pkgname=`echo $1 |sed 's|[^/]\+/\([^/]\+\)|\1|'`
	else
		echo "Bad syntax!"
		usage
		exit 1
	fi

	if [ "$repo" == "frugalware" ]; then
		dir="source"
	elif [ "$repo" == "extra" ]; then
		dir="extra/source"
	else
		echo "No such repo!"
		exit 1
	fi
	if [ "$verbose" == 1 ]; then
		catcmd="cat Changelog"
	fi
	ssh $lopts $host "cd $path_to_repo/$dir/../frugalware-${arch:-`arch`} && arch=${arch:-`arch`} sudo -u $sudouser updatesync upd $repo-current.fdb ../source/$group/$pkgname/FrugalBuild && cd $path_to_repo/$dir/$group/$pkgname && sudo -u $sudouser genchangelog; $catcmd"
}

die()
{
	echo -e "$0: $*"
	exit 1
}

update()
{
	if [ -z "$1" ]; then
		repo=$reponame
	else
		repo=$1
	fi
	# search for a mirror
	[ -e /etc/pacman.d/frugalware-current ] || \
		die "Can't find any mirror!\nMaybe try a 'pacman -S pacman'";
	server=`grep ^Server /etc/pacman.d/frugalware-current |sed -n 's/.*= \(.*\)/\1/;1 p'`/..
	# server="http://darcs.frugalware.org/repos/frugalware-current"
	if [ -d $fst_root/$repo ]; then
		cd $fst_root/$repo &&
		darcs pull
	else
		mkdir $fst_root &&
		cd $fst_root && darcs  get --partial $server
	fi
}

chk_updated()
{
	if [ ! -d $1 ]; then
		echo "error: could not find FrugalBuild scripts in $1"
		echo "       have you used 'repoman upd' yet?"
		exit 1
	fi
}

search()
{
	chk_updated $fst_root
	[ -z "$*" ] || grepcmd="|grep $*"
	eval "find $fst_root/$reponame/{source,extra/source} -name FrugalBuild |xargs grep ^nobuild= |sed 's|$fst_root/$reponame/\(.*\)/source/\(.*\)/FrugalBuild:.*|\1/\2|' $grepcmd"
}

merge()
{
	chk_updated $fst_root
	dir=`find $fst_root -type d -name "$1"|sed -n '$ p'`
	cd $dir
	makepkg $makepkg_opts
}

[ -e /etc/repoman.conf ] && . /etc/repoman.conf || \
	die "Can't find /etc/repoman.conf!"
[ -e ~/.repoman.conf ] && . ~/.repoman.conf

# initializating variables
version='0.2.0'

# checking for darcs
which darcs >/dev/null 2>&1
if [ $? != 0 ]; then
	echo "ERROR: Can't find darcs. You can install it with pacman -S darcs."
	exit 1
fi

#pharsing parameters

if ! [ -z "$REPOMAN_LOGIN" ]; then
	lopts="-l $REPOMAN_LOGIN"
	cpopts="$REPOMAN_LOGIN@"
fi

if [ $# -le 0 ]; then
	usage
	exit 0
fi

while [ "$1" != "" ]; do
	case $1 in
		-h|--help)
			usage
			exit 0
		;;
		-v|--verbose)
			 verbose=1
		;;
		-*)
			echo "Wrong parameter!"
			usage
			exit 1
		;;
		cl|changelog)
			shift 1
			changelog $*
		;;
		del|delete)
			shift 1
			delete $*
		;;
		ls|list)
			shift 1
			list $*
			exit 0
		;;
		m|merge)
			shift 1
			merge $*
		;;
		up|upload)
			shift 1
			upload $*
		;;
		upd|update)
			shift 1
			update $*
		;;
		s|search)
			shift 1
			search $*
		;;
	esac
	shift 1
done
