.TH "REPOMAN" "1" "May 2005" "Frugalware 0.3" "pacman-tools"
.SH NAME
repoman \- Frugalware's program to maintain packages via darcs and ssh
.SH SYNOPSIS
\fBrepoman\fR [\fIglobal options\fR] [\fIcommand\fR] [\fIcommand options\fR]
.SH DESCRIPTION
.BR repoman
is meant for Frugalware developers to upload or delete source
tarballs, fpm packages and generate changelogs.
.br
Note: \fBrepoman\fR only runs \fIinside\fR a darcs repository.
.SH USAGE
A typical package update should be done as follows:
.TP
0) Get/update the repo, make changes, build the package:

.BR Note:
You're recommended to you a mirror sever and the --partial option!

Example for the first time:

darcs get --partial http://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/

cd frugalware-current

echo "yourname <email@addr.ess>" >_darcs/prefs/author

echo 'username@darcs.frugalware.org:/home/ftp/pub/frugalware/frugalware-current' >_darcs/prefs/defaultrepo

echo 'push apply-as vmiklos' >> _darcs/prefs/defaults

If you already got the repo a simple 'darcs pull' should be enough.

Now time to edit the FrugalBuild, make changes, darcs record, build the new package, etc.

.TP
1) Delete the old source packages(s).

If you do only a rebuild, then, of couse, skip this step. For example:

repoman del source/base/readline/readline-5.0.tar.gz

.TP
2) Delete the old fpm package.

For example:

repoman del extra/frugalware/k3b-i18n-0.11-1.fpm

.TP
3) Push the FrugalBuild/.install/etc patch.

Here you only have to do a simple 'darcs push'.

.TP
4) Upload the source package(s).

For example:

repoman up zsh-4.2.5.tar.bz2 /source/apps/zsh/
repoman up zsh-doc-4.2.5.tar.bz2 /source/apps/zsh/

.TP
5) Upload the fpm package:

For example:

repoman up sendmail-8.13.4-1.fpm extra/frugalware/

.TP
6) Generate a Changelog and update the .fdb database:

For example:

repoman cl base/perl

.SH COMMANDS
.TP
.BI cl|changelog " [repository/]category/package"
Generate a Changelog file from darcs patch comments.
.TP
.BI del|delete " file"
Delete a file from FST.

Example: repoman del extra/frugalware/k3b-i18n-0.11-1.fpm
.TP
.BI ls|list " directory [options]"
List the contents of a remote directory.

Example: repoman ls source/base/db/ -l
.TP
.BI up|upload " source destination"
Upload a file to FST.

Example: repoman up cabextract-1.1-1.fpm frugalware/cabextract-1.1-1.fpm
.TP
.BI upd|update " [repo]"
Update a repo in /var/fst. If the option repo parameter omitted, the repoman
will update the frugalware-current repo. If the frugalware-current repo not
yet exists, then repoman will download it (it may take some time!).

.TP
.BI s|search " [regexp]"
Search in those FrugalBuilds which are only available in source form. If the
optional regexp parameter omitted, it'll list all source-only packages.

.SH OPTIONS
.TP
.B -h|--help
Show the help screen.
.TP
.B -v|--verbose
Give verbose output.
.SH ENVIRONMENT
\fBrepoman\fR utilizes the following environment variable:
.PP
.Vb 2
REPOMAN_LOGIN                Use different login name than the current.
.SH AUTHORS
Miklos Vajna <vmiklos@frugalware.org>
.SH "REPORTING BUGS"
Please report bugs to the frugalware-users@frugalware.org mailing list.
.SH "SEE ALSO"
.BR darcs (1),
.BR pacman (8)
