#!/bin/bash

if [ "`pwd|sed 's|.*/\(.*\)|\1|'`" != "emul-extra" ]; then
	echo "where are you?"
	exit 1
fi

darcs pull -a

for i in `chkworld |grep ^Checking |sed 's|.*/\(.*\)-[^-]*\.\.\..*|\1|'`
do
	cd $i
	bumppkg
	repoman rec "version bump"
	repoman -k push
	cd ..
done
