#!/bin/bash

. /usr/lib/frugalware/fwmakepkg

if [ "`pwd|sed 's|.*/\(.*\)|\1|'`" != "emul-extra" ]; then
	echo "where are you?"
	exit 1
fi

if [ "$_F_makepkg_scm" = "git" ]; then
	git pull
else
	darcs pull -a
fi

for i in `chkworld |grep ^Checking |sed 's|.*/\(.*\)-[^-]*\.\.\..*|\1|'`
do
	cd $i
	bumppkg
	repoman rec "version bump"
	repoman -k push
	cd ..
done
