#!/bin/bash
# 
#   syncpkgd
#  
#   Copyright (c) 2006 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

# sanility checks

if [ ! -d /home/syncpkgd ]; then
	echo "can't find my home!"
	exit 1
fi

if [ ! -e /home/syncpkgd/.ssh/id_dsa ]; then
	echo "can't find my dsa key!"
	exit 1
fi

if [ "`whoami`" = "root" ]; then
	if [ -e /var/run/syncpkgd.pid ]; then
		echo "syncpkgd is already running!"
		exit 1
	fi
	# drop privileges and start the real daemon
	su - syncpkgd -c $0 &
	echo $! >/var/run/syncpkgd.pid
else
	# start syncpkg again and again
	while true
	do
		syncpkg
		sleep 2h
	done
fi
