#!/bin/bash
# 
#   syncpkg
#  
#   Copyright (c) 2005-2006 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

if [ -e /etc/syncpkg.conf ]; then
	. /etc/syncpkg.conf
fi

log()
{
	date >>$blogfile
	echo "$@" >>$blogfile
}

in_array()
{
	local i

	needle=$1
	shift 1
	for i in $*
	do
		[ "$i" == "$needle" ] && return 0
	done
	return 1
}

pkglist=`mktemp`

if [ ! -d ~/darcs ]; then
	mkdir ~/darcs
fi
cd ~/darcs

if [ ! -d frugalware-current ]; then
	darcs get --partial syncpkgd@darcs.frugalware.org:/home/ftp/pub/frugalware/frugalware-current >>$blogfile 2>&1
	cd frugalware-current
else
	cd frugalware-current
	darcs pull -a >>$blogfile 2>&1
	# revert changes if there are any
	darcs revert -a >>$blogfile 2>&1
fi

cd tools
python checkpkgs -n|grep "\[O\] `uname -m`"|sed 's/\(.*\)-[^- ]*-[^- ]* .*/\1/' >$pkglist

cd ..
log "number of pkgs to build: `wc -l $pkglist|sed 's/\(.*\) .*/\1/'`"

# cleanup the logs and the chroot
[ ! -z "$days" ] || days="7"
find /var/log/syncpkg -mtime +$days -exec rm -vrf {} \;
rmdir /var/log/syncpkg/* 2>/dev/null

i=0
for pkg in `cat $pkglist`
do
	if in_array $pkg ${ignore[@]}; then
		continue
	fi

	CWD=`pwd`
	# 4 will find pkgs from extra, but not under _darcs
	cd `find . -type d -maxdepth 4 -name $pkg 2>/dev/null`
	rm -f *fpm *.log
	log "making package: $pkg"
	sudo makepkg -RC >>$mlogfile 2>&1
	# TODO: at this point maybe some dirs are not umounted perfectly
	# till we find a real sollution (sudo for umount?), here is a workaround:
	# for i in `mount|grep /var/chroot.vmiklos|sed 's/.* on \([^ ]*\) .*/\1/'`; do sudo umount $i; done
	# if $CHROOTDIR is /var/chroot.vmiklos
	sudo makepkg -RLuk >>$mlogfile 2>&1
	ret=$?
	log "finished making package $pkg with exit code $ret"
	if [ -e *.log ]; then
		echo $ret >`ls *.log`.exitcode
		[ -d $logdir ] || mkdir -p $logdir
		mv *.log *.log.exitcode $logdir
	fi
	[ "$ret" == "0" ] && rf -CPUL -k -f *fpm >>$mlogfile 2>&1
	cd $CWD
	i=$(($i+1))

	if [ "$i" -ge "$maxpkgs" ]; then
		break
	fi
done
rm $pkglist
log "build finished, pkgs built: $i"
