#!/bin/bash

. /usr/lib/frugalware/fwmakepkg

if [ "$1" == "-h" -o "$1" == "--help" ]; then
	man synclib32
	exit $?
fi

if [ "$1" == "-v" -o "$1" == "--version" ]; then
	pacman-g2 -Q pacman-tools
	exit $?
fi

if [ "`pwd|sed 's|.*/\(.*\)|\1|'`" != "lib32-extra" ]; then
	echo "Where are you?"
	echo "Wrong folder , see man synclib32"
	exit 1
fi

if [ "$F_makepkg_scm" = "git" ]; then
	git pull
else
	darcs pull -a
fi

for i in `chkworld |grep ^Checking |sed 's|.*/\(.*\)-[^-]*\.\.\..*|\1|'`
do
	cd $i
	bumppkg
	repoman rec "synclib32 - Auto sync from 32bit repo"
	repoman -k push
	cd ..
done
