#!/bin/bash
# 
#   syncpkg
#  
#   Copyright (c) 2005-2006 by Miklos Vajna <vmiklos@frugalware.org>
#  
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
# 
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
#   USA.
#

if [ -e /etc/syncpkg.conf ]; then
	. /etc/syncpkg.conf
fi

log()
{
	date >>$blogfile
	echo "$@" >>$blogfile
}

in_array()
{
	local i

	needle=$1
	shift 1
	for i in $*
	do
		[ "$i" == "$needle" ] && return 0
	done
	return 1
}

pkglist=`mktemp`

if [ ! -d ~/darcs ]; then
	mkdir ~/darcs
fi
cd ~/darcs

if [ -z "$1" ]; then
	echo "parameter #1 (tree) is missing!"
	exit 1
else
	tree=$1
fi

if [ ! -d $tree ]; then
	darcs get --partial syncpkgd@darcs.frugalware.org:/home/ftp/pub/frugalware/frugalware-$tree >>$blogfile 2>&1
	mv frugalware-$tree $tree
	cd $tree
else
	cd $tree
	darcs pull -a >>$blogfile 2>&1
	# revert changes if there are any
	darcs revert -a >>$blogfile 2>&1
fi

cd tools
python checkpkgs -t $tree -n|grep "\[O\] `uname -m`"|sed 's/\(.*\)-[^- ]*-[^- ]* .*/\1/' >$pkglist

cd ..
log "number of pkgs to build: `wc -l $pkglist|sed 's/\(.*\) .*/\1/'`"

# cleanup the logs and the chroot
[ ! -z "$days" ] || days="7"
find /var/log/syncpkg -mtime +$days -exec rm -vrf {} \; >>$mlogfile 2>&1
rmdir /var/log/syncpkg/* 2>/dev/null

i=0
for pkg in `cat $pkglist`
do
	if in_array $pkg ${ignore[@]}; then
		continue
	fi

	CWD=`pwd`
	cd `find source -maxdepth 2 -type d -name $pkg`
	rm -f *fpm *.log
	log "making package: $pkg"
	echo "$pkg" >/tmp/sync.pkg
	sudo makepkg -t $tree -C >>$mlogfile 2>&1
	sudo makepkg -t $tree -uck >>$mlogfile 2>&1
	ret=$?
	log "finished making package $pkg with exit code $ret"
	rm /tmp/sync.pkg
	if [ -e *.log ]; then
		echo $ret >`ls *.log`.exitcode
		[ -d $logdir ] || mkdir -p $logdir
		mv *.log *.log.exitcode $logdir
	fi
	[ "$ret" == "0" ] && rf -v $tree -CPUL -k -f *fpm >>$mlogfile 2>&1
	cd $CWD
	i=$(($i+1))

	if [ "$i" -ge "$maxpkgs" ]; then
		break
	fi
done
rm $pkglist
log "build finished, pkgs built: $i"
