.TH "MKISO" "1" "Jun 2006" "Frugalware 0.5" "pacman-tools"
.SH NAME
mkiso \- Frugalware's program to generate ISO9660 images
.SH SYNOPSIS
\fBmkiso\fR [\f  -h \fR] [\fI -c | volumes.xml\fR ]
.SH DESCRIPTION
.BR mkiso
is meant for anyone who wants to generate (custom) iso images
from the Frugalware Source Tree.
.SH USAGE
A typical iso generation should be done as follows:
.TP
Create a working directory:

$ mkdir -p ~/iso

$ cd ~/iso

.TP
Copy the descriptor xml template to there:

$ cp /usr/share/doc/pacman-tools-*/volumes.xml ./

.TP
Change the fst_root to something like:

<fst_root>/home/vmiklos/iso</fst_root>

.TP
In this example we create a netinstall iso, so leave only the following entry:

.nf
<volume>
	<arch>i686</arch>
	<media>net</media>
</volume>
.fi

.TP
Now we need a few base files:

NOTE: feel free to choose a different rsync mirror from /etc/repoman.conf!

$ rsync -avP rsync://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/AUTHORS ./

$ rsync -avP rsync://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/ChangeLog.txt ./

$ rsync -avP rsync://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/LICENSE ./

.TP
We need documentation:

$ rsync -avP rsync://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/docs ./

.TP
Then the kernel and the initrd:

$ rsync -avP rsync://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/boot .

.TP
Finally the packages and package databases. For the netinstall we can ignore the fpms:

$ rsync -avP rsync://ftp5.frugalware.org/packages/frugalware/pub/frugalware/frugalware-current/frugalware-i686 ./ --exclude '*fpm'

.TP
Ok, we have the necessary files, let's make the iso!

$ mkiso

.SH THE XML FILE

In the xml file primarily you should define the required volumes. The media
type of the volume is required at least. The media can be "net", "cd", or "dvd". The
"net" will not contain any fpm packages. The only difference between "cd" and "dvd"
is the default size. You can define the arch, which defaults to the machine
hardware name. For a cd or dvd a serial tag is required, 1 or the 1st cd and
so on. You can define a custom cd/dvd size with the size tag.

After defining the volumes, you must supply the root of the Frugalware
Source Tree with the fst_root tag. Other optional tags include out_dir
[defaults to fst_root], version [timestamp] and codename [-current].

.SH HACKING

Probably the most changing part is the initrd and the kernel. You can generate
them from the 'setup' darcs repo.

.SH OPTIONS
.TP
.B -h|--help
Show the help screen.
.TP
.B -c|--count
Do not generate the isos, just print out the number of required isos for the
given size.
.TP
.B -s|--stable
Assume that the given repo is a -stable one, so that there will be a
frugalware.fdb under the frugalware-<arch> directory, not a
frugalware-current.fdb.
.TP
.B -f|--file <volumes.xml>
By default, mkiso searches for the file named "volumes.xml". If you want a
different one, then just specify it.
.SH AUTHORS
Written by Miklos Vajna.
.SH "REPORTING BUGS"
Please report bugs to http://bugs.frugalware.org/.
.SH "SEE ALSO"
.BR darcs (1),
.BR pacman (8)
