all: current stable

current:
	python ../mirrors.py frugalware-current frugalware-current ~/darcs/homepage-ng/frugalware/xml/mirrors2.xml current

stable:
	python ../mirrors.py frugalware-stable frugalware ~/darcs/homepage-ng/frugalware/xml/mirrors2.xml stable
