all: current stable

current:
	python ../tools/mirrors.py frugalware-current frugalware-current ~/git/homepage-ng/frugalware/xml/mirrors2.xml current

stable:
	python ../tools/mirrors.py frugalware-stable frugalware ~/git/homepage-ng/frugalware/xml/mirrors2.xml stable
